runtime: python
env: flex

handlers:
  - url: /js
  static_dir: js

  - url: /.*
  script: main.app


runtime_config:
  python_version: 3

env_variables:
  CLOUD_STORAGE_BUCKET: staging.ranger-convo-ui.appspot.com

