runtime: python
env: flex

handlers:
  - url: /js
  static_dir: js

entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
  CLOUD_STORAGE_BUCKET: <your-cloud-storage-bucket>


